server:
  jwt:
    enabled: true
    configs:
      - issuer_url: https://test-issuer.example.com
        jwk_cert_file: configs/dev-jwks.json
        header: Authorization
        identity_claim: email

entities:
  - kind: Cluster
    plural: clusters
    spec_schema_name: ClusterSpec
    required_adapters: [validation, dns, pullsecret, hypershift]
    name_min_len: 3
    name_max_len: 53
    require_spec_schema: true
